.TH "file" 3 "Wed Dec 14 2022" "Version 1.0" "Myshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "struct \fBfile\fP * \fBpun\fP"
.br
.ti -1c
.RI "struct stat \fBsb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBls\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "char* name"
File name 
.PP
Definition at line \fB17\fP of file \fBls\&.c\fP\&.
.SS "struct \fBfile\fP* pun"
Pointer to file i-node 
.PP
Definition at line \fB18\fP of file \fBls\&.c\fP\&.
.SS "struct stat sb"
File's i-node 
.PP
Definition at line \fB19\fP of file \fBls\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Myshell from the source code\&.
