.TH "option" 3 "Wed Dec 14 2022" "Version 1.0" "Myshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
option
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBl_info\fP"
.br
.ti -1c
.RI "int \fBa_hidden\fP"
.br
.ti -1c
.RI "int \fBdesired\fP"
.br
.ti -1c
.RI "int \fBhelp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB22\fP of file \fBls\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "int a_hidden"
Flag for printing all the files (hidden included) 
.PP
Definition at line \fB24\fP of file \fBls\&.c\fP\&.
.SS "int desired"
Flag for desired output: 0 files, 1 directories, 2 all 
.PP
Definition at line \fB25\fP of file \fBls\&.c\fP\&.
.SS "int help"
Flag for printing help 
.PP
Definition at line \fB26\fP of file \fBls\&.c\fP\&.
.SS "int l_info"
Flag for printing the files' i-nodes 
.PP
Definition at line \fB23\fP of file \fBls\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Myshell from the source code\&.
