.TH "src/pwd.c" 3 "Wed Dec 14 2022" "Version 1.0" "Myshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/pwd.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.RI "This function gets the current path and prints it to stdout\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
This function gets the current path and prints it to stdout\&. 
.PP
\fBReturns\fP
.RS 4
Returns 0 on success, 1 on error\&. 
.RE
.PP

.PP
Definition at line \fB14\fP of file \fBpwd\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Myshell from the source code\&.
